export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACT_PAGE: "SET_ALL_CONTACT_PAGE",
  SET_CURRENT_CHAT_USER: "SET_CURRENT_CHAT_USER",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  ADD_MESSAGE: "ADD_MESSAGE",
  RELOAD: "RELOAD",
};
